### PR TITLE
🐛 Fix ability timers

### LINKED ISSUE #366: 🚑️ UI Ability Timers

### PR DESCRIPTION
**Pull request by Timsel1**
## Content

Links the new ability system to the UI, which is now part of the player prefab, old UI and GameOverCanvas need to be removed from every scene. The font for the cooldown has also been changed to match the font we use in every other part of the game. (Yes I did clean up the code)

### Updated
`Assets/Prefabs/Player/Player_1.prefab` : Was updated. UI linked to player and abilities was added to the player prefab.
`Assets/Scripts/Ability/AbilityManager.cs` : Was updated. Now also controls the UI for the abilities.
`Assets/Scripts/Ability/RogueApeStudio.Crusader.Ability.asmdef` : Was updated. A reference to TMPro was added.

## Testing

The feature / Bugfix can be testing by following these steps:

CooldownUI

Closes #366

### CODE REVIEW

File: Assets/Scripts/Ability/AbilityManager.cs [hunk 1]
```diff
@@ -45,6 +59,8 @@ public class AbilityManager : MonoBehaviour
         private int _slotNumber;
         private Vector3 _position;
         private bool _slotActive = false;
+        private readonly int[] _uiTimers = new int[3];
```
Comment (NathanThus) [inline Assets/Scripts/Ability/AbilityManager.cs:62]: I'd prefer to see a constant here.

File: Assets/Scripts/Ability/AbilityManager.cs [hunk 2]
```diff
@@ -242,6 +271,39 @@ internal void RemoveEffect()
...
 
+        private void StartCooldowns(float cooldown)
+        {
+            if (_abilityTokenSources[_slotNumber] != null)
+            {
+                _abilityTokenSources[_slotNumber]?.Cancel();
+                _abilityTokenSources[_slotNumber]?.Dispose();
+            }
+
+            _abilityTokenSources[_slotNumber] = new CancellationTokenSource();
```
Comment (NathanThus) [inline Assets/Scripts/Ability/AbilityManager.cs]: This really isn't how you're supposed to use this, as cancelling throws an exception.

**Review by NathanThus — APPROVED** [review]
