### PR TITLE
🐛 Fix dash direction with no input

### LINKED ISSUE #107: 🐛 Player dash animation rolling in the wrong direction

### PR DESCRIPTION
**Pull request by Timsel1**
## Content

Player now dashes in the direction the character is looking when no input is detected.

### Updated
`Assets/Scripts/Player/Movement/PlayerController.cs` : Was updated. logic to save last movement input was deleted to use vector3.forward.

## Testing

The feature / Bugfix can be testing by following these steps:

DashDirectionFix

Closes #107

### CODE REVIEW

File: Assets/Scripts/Player/Movement/PlayerController.cs [hunk 1]
```diff
@@ -59,27 +59,12 @@ private void OnDash(InputAction.CallbackContext context)
...
-                else
-                {
-                    if (_lastMovementDirection != Vector3.zero)
-                    {
-                        dashDirection = _lastMovementDirection.normalized;
-                    }
-                }
-
-                Vector3 dashForce = dashDirection * _dashSpeed;
+                Vector3 dashForce = _rb.transform.forward * _dashSpeed;
```
Comment (NathanThus) [inline Assets/Scripts/Player/Movement/PlayerController.cs]: Serialize a reference to `_rb.transform`, as calling it is a decently expensive operation.

**Review by NathanThus — CHANGES_REQUESTED** [review]

**Review by NathanThus — APPROVED** [review]
